#.travis.yml

language: node_js
node_js:
  - "node"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --aot=true --prod --build-optimizer --verbose --progress=true --delete-output-path --extract-licenses --subresource-integrity --stats-json
  - du -sh dist/

#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
